### ISSUE TITLE
Can't control mouse cursor when evdevshift is configured for HAT

### ISSUE THREAD

**Issue by mwozny123** [uglyDwarf/evdevshift#9]
Can't control mouse cursor when evdevshift is configured for HAT.

Configuration:
[Saiteck_AV8R-01-cursor_problem.conf.txt](https://github.com/uglyDwarf/evdevshift/files/416707/Saiteck_AV8R-01-cursor_problem.conf.txt)

Video:
https://vimeo.com/178736801

ps: for me low priority. Axis mapping higher;)

**Comment by uglyDwarf** [comment]
I'm working on it, unfortunately real life is interfering, so it doesn't go as swiftly as I'd like to...
Kind regards,
Michal

**Comment by mwozny123** [comment]
Cool. 
Personally I would be happier from mapping "shift"+axis to new axis;)

Thanks
Marcin

**Comment by uglyDwarf** [comment]
Hi,
I just committed the new stuff - take a look at the test.conf; I added conditional mapping of axis to a new one (not sure it makes sense to make such mapping unconditionally; but if needed, I can add it).
The "new_axis" does it...
As for hijacking mouse/not being recognized as joystick, I'll take a peek at those heuristics and see if I can make the program smart enough to stay in the joystick category no matter what...
Let me know if what I did works for you...
Kind regards,
Michal

**Comment by mwozny123** [comment]
Re-tests after last updates - new issue no new joystick (evdevshift joystick) was not visible in jstest-gtk (only oryginal joystick), mouse problem still exists.

logs:

```
$ ./evdevshift --config presets/Saiteck_AV8R-01-cursor_problem.conf 
Parsing file 'presets/Saiteck_AV8R-01-cursor_problem.conf'.
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
Device: 'Saitek AV8R Joystick'.
Names defined:
Name def: Axis ABS_HAT0Y => 17
Name def: Axis ABS_HAT0X => 16
Name def: Axis ABS_THROTTLE => 6
Name def: Axis ABS_RZ => 5
Name def: Axis ABS_Z => 2
Name def: Axis ABS_Y => 1
Name def: Axis ABS_X => 0
Name def: Button BUTTON_12D => 301
Name def: Button BUTTON_12C => 300
Name def: Button BTN_BASE6 => 299
Name def: Button BTN_BASE5 => 298
Name def: Button BTN_BASE4 => 297
Name def: Button BTN_BASE3 => 296
Name def: Button BTN_BASE2 => 295
Name def: Button BTN_BASE => 294
Name def: Button BTN_PINKIE => 293
Name def: Button BTN_TOP2 => 292
Name def: Button BTN_TOP => 291
Name def: Button BTN_THUMB2 => 290
Name def: Button BTN_THUMB => 289
Name def: Button BTN_TRIGGER => 288
State:
      Button BUTTON_12D => 301
        Axis ABS_HAT0Y (17) will be mapped to buttons BUTTON_12C (300)/ BUTTON_12D (301).
        Axis ABS_HAT0X (16) will be mapped to buttons BUTTON_12E (302)/ BTN_DEAD (303).
        Button BTN_BASE6 (299) will be mapped to BTN_A (304).
        Button BTN_BASE5 (298) will be mapped to BTN_B (305).
        Button BTN_BASE4 (297) will be mapped to BTN_C (306).
        Button BTN_BASE3 (296) will be mapped to BTN_X (307).
        Button BTN_BASE2 (295) will be mapped to BTN_Y (308).
        Button BTN_BASE (294) will be mapped to BTN_Z (309).
        Button BTN_PINKIE (293) will be mapped to BTN_TL (310).
        Button BTN_TOP2 (292) will be mapped to BTN_TR (311).
State:
      Button BUTTON_12C => 300
        Axis ABS_HAT0Y (17) will be mapped to buttons BTN_TL2 (312)/ BTN_TR2 (313).
        Axis ABS_HAT0X (16) will be mapped to buttons BTN_SELECT (314)/ BTN_START (315).
        Button BTN_BASE6 (299) will be mapped to BTN_MODE (316).
        Button BTN_BASE5 (298) will be mapped to BTN_THUMBL (317).
        Button BTN_BASE4 (297) will be mapped to BTN_THUMBR (318).
        Button BTN_BASE3 (296) will be mapped to BUTTON_13F (319).
        Button BTN_BASE2 (295) will be mapped to BTN_TOOL_PEN (320).
        Button BTN_BASE (294) will be mapped to BTN_TOOL_RUBBER (321).
        Button BTN_PINKIE (293) will be mapped to BTN_TOOL_BRUSH (322).
        Button BTN_TOP2 (292) will be mapped to BTN_TOOL_PENCIL (323).
Axis Maps:
File 'presets/Saiteck_AV8R-01-cursor_problem.conf' opened.
New device created.
```

**Comment by uglyDwarf** [comment]
Could you please add what evtest has to say about the new device? Assuming the /dev/input/eventX is created - if no, please let me know...
I'm interested in what evtest reports about the device (axes, buttons, ...).
Also can you check what /var/log/Xorg.log has to say about the device (is the device recognized as mouse, or tablet?)...

Kind regards,

Michal

**Comment by mwozny123** [comment]
evtest doesn't seem to see any addional devices, nor I see it in jstest-gtk (and there usually was one more)

```
$ evtest
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event5:      Saitek AV8R Joystick
Select the device event number [0-5]: 5
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x6a3 product 0x461 version 0x100
Input device name: "Saitek AV8R Joystick"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 288 (BTN_TRIGGER)
    Event code 289 (BTN_THUMB)
    Event code 290 (BTN_THUMB2)
    Event code 291 (BTN_TOP)
    Event code 292 (BTN_TOP2)
    Event code 293 (BTN_PINKIE)
    Event code 294 (BTN_BASE)
    Event code 295 (BTN_BASE2)
    Event code 296 (BTN_BASE3)
    Event code 297 (BTN_BASE4)
    Event code 298 (BTN_BASE5)
    Event code 299 (BTN_BASE6)
    Event code 300 (?)
    Event code 301 (?)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    512
      Min        0
      Max     1023
      Fuzz       3
      Flat      63
    Event code 1 (ABS_Y)
      Value    515
      Min        0
      Max     1023
      Fuzz       3
      Flat      63
    Event code 2 (ABS_Z)
      Value    130
      Min        0
      Max      255
      Flat      15
    Event code 5 (ABS_RZ)
      Value    128
      Min        0
      Max      255
      Flat      15
    Event code 6 (ABS_THROTTLE)
      Value      0
      Min        0
      Max      255
      Flat      15
    Event code 16 (ABS_HAT0X)
      Value      0
      Min       -1
      Max        1
    Event code 17 (ABS_HAT0Y)
      Value      0
      Min       -1
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1473446932.438634, type 3 (EV_ABS), code 1 (ABS_Y), value 514
Event: time 1473446932.438634, -------------- SYN_REPORT ------------
Event: time 1473446932.478697, type 3 (EV_ABS), code 1 (ABS_Y), value 513
Event: time 1473446932.478697, -------------- SYN_REPORT ------------
Event: time 1473446932.526632, type 3 (EV_ABS), code 2 (ABS_Z), value 131
Event: time 1473446932.526632, -------------- SYN_REPORT ------------
Event: time 1473446932.558696, type 3 (EV_ABS), code 1 (ABS_Y), value 515
Event: time 1473446932.558696, -------------- SYN_REPORT ------------
Event: time 1473446932.598633, type 3 (EV_ABS), code 2 (ABS_Z), value 130
Event: time 1473446932.598633, -------------- SYN_REPORT ------------
Event: time 1473446932.606687, type 3 (EV_ABS), code 1 (ABS_Y), value 514
(..)

```

tail from /var/log/Xorg.0.log (after couple sec I terminated evdevshift, to be able to use the mouse, that's why there's a "remove" in log)

```
[  1894.262] (--) NVIDIA(GPU-0): 
[  3934.319] (II) config/udev: Adding input device evdevshift: Saitek AV8R Joystick (/dev/input/event14)
[  3934.319] (**) evdevshift: Saitek AV8R Joystick: Applying InputClass "evdev tablet catchall"
[  3934.319] (II) Using input driver 'evdev' for 'evdevshift: Saitek AV8R Joystick'
[  3934.319] (**) evdevshift: Saitek AV8R Joystick: always reports core events
[  3934.319] (**) evdev: evdevshift: Saitek AV8R Joystick: Device: "/dev/input/event14"
[  3934.319] (--) evdev: evdevshift: Saitek AV8R Joystick: Vendor 0x6a3 Product 0x461
[  3934.319] (--) evdev: evdevshift: Saitek AV8R Joystick: Found absolute axes
[  3934.319] (--) evdev: evdevshift: Saitek AV8R Joystick: Found x and y absolute axes
[  3934.319] (--) evdev: evdevshift: Saitek AV8R Joystick: Found absolute tablet.
[  3934.319] (II) evdev: evdevshift: Saitek AV8R Joystick: Configuring as tablet
[  3934.319] (**) evdev: evdevshift: Saitek AV8R Joystick: YAxisMapping: buttons 4 and 5
[  3934.319] (**) evdev: evdevshift: Saitek AV8R Joystick: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[  3934.320] (**) Option "config_info" "udev:/sys/devices/virtual/input/input17/event14"
[  3934.320] (II) XINPUT: Adding extended input device "evdevshift: Saitek AV8R Joystick" (type: TABLET, id 12)
[  3934.320] (II) evdev: evdevshift: Saitek AV8R Joystick: initialized for absolute axes.
[  3934.320] (**) evdevshift: Saitek AV8R Joystick: (accel) keeping acceleration scheme 1
[  3934.321] (**) evdevshift: Saitek AV8R Joystick: (accel) acceleration profile 0
[  3934.321] (**) evdevshift: Saitek AV8R Joystick: (accel) acceleration factor: 2.000
[  3934.321] (**) evdevshift: Saitek AV8R Joystick: (accel) acceleration threshold: 4
[  3982.287] (II) config/udev: removing device evdevshift: Saitek AV8R Joystick
[  3982.306] (II) evdev: evdevshift: Saitek AV8R Joystick: Close
[  3982.306] (II) UnloadModule: "evdev"

```

**Comment by uglyDwarf** [comment]
Hello,
in the meantime I managed to reproduce the problem and your logs confirm what I see - the device is recognized as tablet because of presence of the BTN_TOOL_PEN button... And evtest doesn't report it probably because it is grabbed by the X server (or it has wrong permissions)...
Anyway, I'm working on a fix...
Kind regards,
Michal

**Comment by uglyDwarf** [comment]
I just committed a fix that works in the case that I see...
Add the following line to your config:
`avoid button BTN_TOOL_PEN, button BTN_STYLUS`

This will instruct evdevshift to skip those buttons when mapping the real ones; with those two buttons the new device should not be mistaken for tablet anymore...
Kind regards,
Michal

**Comment by mwozny123** [comment]
~~I did 'git pull' and something's seems to be wrong now. Should I try to do a fresh 'git clone'?~~

BTW wouldn't it be better if the `avoid button BTN_TOOL_PEN, button BTN_STYLUS` be a default option?

~~here's log:~~ (explanation: this was run for snap evdevshift without HW access. No need to bother).

```
$ evdevshift --config presets/Saiteck_AV8R-01-cursor_problem.conf 
Can't open file 'presets/Saiteck_AV8R-01-cursor_problem.conf'
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
Device named '(null)' NOT opened.

marcin@ubuntu:~/evdevshift$ evdevshift 
Usage examples:
To create config template:
evdevshift --device /dev/input/event12 --template x52.conf
To create a virtual device based on the config:
evdevshift --config x52.conf

marcin@ubuntu:~/evdevshift$ evtest
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event6:      Saitek AV8R Joystick
Select the device event number [0-6]: ^V^C
marcin@ubuntu:~/evdevshift$ evdevshift --device /dev/input/event6 --template x52.conf
open: Permission denied
Device '/dev/input/event6' NOT opened.
```

**Comment by mwozny123** [comment]
Ignore my previous problem. I forgot that I installed snap evdevshift, it was run instead of evdevshift from current dir ("./").

It works (doesn't move mouse cursor) but in the log there's entry `will be mapped to BTN_TOOL_PENCIL` I don't know if that's ok for you or not?

Full log:

```
$ ./evdevshift --config presets/Saiteck_AV8R-01-cursor_problem.conf 
Parsing file 'presets/Saiteck_AV8R-01-cursor_problem.conf'.
Avoid BTN_TOOL_PEN.
Avoid BTN_STYLUS.
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
open: Permission denied
Device: 'Saitek AV8R Joystick'.
Names defined:
Name def: Axis ABS_HAT0Y => 17
Name def: Axis ABS_HAT0X => 16
Name def: Axis ABS_THROTTLE => 6
Name def: Axis ABS_RZ => 5
Name def: Axis ABS_Z => 2
Name def: Axis ABS_Y => 1
Name def: Axis ABS_X => 0
Name def: Button BUTTON_12D => 301
Name def: Button BUTTON_12C => 300
Name def: Button BTN_BASE6 => 299
Name def: Button BTN_BASE5 => 298
Name def: Button BTN_BASE4 => 297
Name def: Button BTN_BASE3 => 296
Name def: Button BTN_BASE2 => 295
Name def: Button BTN_BASE => 294
Name def: Button BTN_PINKIE => 293
Name def: Button BTN_TOP2 => 292
Name def: Button BTN_TOP => 291
Name def: Button BTN_THUMB2 => 290
Name def: Button BTN_THUMB => 289
Name def: Button BTN_TRIGGER => 288
State:
      Button BUTTON_12D => 301
        Axis ABS_HAT0Y (17) will be mapped to buttons BUTTON_12C (300)/ BUTTON_12D (301).
        Axis ABS_HAT0X (16) will be mapped to buttons BUTTON_12E (302)/ BTN_DEAD (303).
        Button BTN_BASE6 (299) will be mapped to BTN_A (304).
        Button BTN_BASE5 (298) will be mapped to BTN_B (305).
        Button BTN_BASE4 (297) will be mapped to BTN_C (306).
        Button BTN_BASE3 (296) will be mapped to BTN_X (307).
        Button BTN_BASE2 (295) will be mapped to BTN_Y (308).
        Button BTN_BASE (294) will be mapped to BTN_Z (309).
        Button BTN_PINKIE (293) will be mapped to BTN_TL (310).
        Button BTN_TOP2 (292) will be mapped to BTN_TR (311).
State:
      Button BUTTON_12C => 300
        Axis ABS_HAT0Y (17) will be mapped to buttons BTN_TL2 (312)/ BTN_TR2 (313).
        Axis ABS_HAT0X (16) will be mapped to buttons BTN_SELECT (314)/ BTN_START (315).
        Button BTN_BASE6 (299) will be mapped to BTN_MODE (316).
        Button BTN_BASE5 (298) will be mapped to BTN_THUMBL (317).
        Button BTN_BASE4 (297) will be mapped to BTN_THUMBR (318).
        Button BTN_BASE3 (296) will be mapped to BUTTON_13F (319).
        Button BTN_BASE2 (295) will be mapped to BTN_TOOL_RUBBER (321).
        Button BTN_BASE (294) will be mapped to BTN_TOOL_BRUSH (322).
        Button BTN_PINKIE (293) will be mapped to BTN_TOOL_PENCIL (323).
        Button BTN_TOP2 (292) will be mapped to BTN_TOOL_AIRBRUSH (324).
Axis Maps:
File 'presets/Saiteck_AV8R-01-cursor_problem.conf' opened.
New device created.
```

BTW wouldn't it be better if the avoid button BTN_TOOL_PEN, button BTN_STYLUS be a default option?

**Comment by uglyDwarf** [comment]
Hello,
the thing is this - X server by default captures mice, tablets, touchpads... Udev uses heuristic algorithm to guess what kind of device it got by looking at axes, buttons and other characteristics...
See https://cgit.freedesktop.org/systemd/systemd/tree/src/udev/udev-builtin-input_id.c , test_pointers function...
The tablet is recognized either by a presence of BTN_TOOL_PEN or BTN_STYLUS; if none of them is present, the device won't be recognized as a tablet... Unfortunately joystick is only a "fallback" - all other options are checked first... I'll have to go through it thoroughly to see what other combinations can cause problems...
Now as for hardcoding those ignore values, I'd like to avoid that; the thing is, that the procedure is heuristic and can change in the future... What I'm thinking of is adding the line to the template - that way it can be customized and won't cause problems by default - how about that?
Kind regards,

Michal

**Comment by mwozny123** [comment]
Cool, I think generating this line is OK. 

BTW Readme file is not up to date (build  steps now use ". /configure" before "make" ).
